### ISSUE TITLE
Tooltip templates

### ISSUE THREAD

**Issue by Eralmidia** [IgniteUI/igniteui-angular-charts#22]
I'm a bit confused as to how to create custom tooltips. I have a data chart, with a column series. But when assigning the tooltip template to the series, it doesn't show:
![image](https://user-images.githubusercontent.com/12936286/66026583-6f7d8f00-e4f9-11e9-9448-bb66054ab3ae.png)

![image](https://user-images.githubusercontent.com/12936286/66027051-6c36d300-e4fa-11e9-95fe-47410092d1f8.png)

**Comment by gmurray81** [comment]
hmm... since there is space for the content reserved. I wonder if perhaps the font color is just matching the background?

**Comment by gmurray81** [comment]
For example, here would be the most basic custom tooltip example:

https://stackblitz.com/edit/custom-tooltips?file=src%2Fapp%2Fdata-chart-type-category-series%2Fdata-chart-type-category-series.component.html

I think perhaps something has set the ambient font color to white, and because that is matching the default tooltip container background, the text is getting lost. IIRC there is some css to affect our default tooltip container background, or you can also retemplate that container to adjust how it looks, if need be.

**Comment by Eralmidia** [comment]
Ah, yes, you are probably right abut that. Are the chart modules suppose to be part of the theme-system, like the rest of the igx-components? Even if I set the bg color of my div, it seems there are some padding applied which I need to override:
![image](https://user-images.githubusercontent.com/12936286/66048509-f64a6000-e529-11e9-8f9b-79bcd6997163.png)

![image](https://user-images.githubusercontent.com/12936286/66048579-1417c500-e52a-11e9-8f8a-397365fd0b1c.png)

**Comment by gmurray81** [comment]
we'll be simplifying this, but you can use: 
```css
.ig-tooltip-container {
    background: #1E1E1E;
    color: #AAAAAA;
}
.ig-tooltip-container-background {
    background: #1E1E1E !important;
    color: #AAAAAA !important;
}
```

**Comment by gmurray81** [comment]
next release should have some included dark themes btw. The theming doesn't work in precisely the same way. It eschews css precompilation schemes for semantically named css custom properties.

**Comment by gmurray81** [comment]
oh, nm, you can already do this the better way:

```css
.ig-data-chart {
  --tooltip-container-background-color: #1E1E1E;
  --tooltip-container-text-color: #AAAAAA
}
```
